# This file was generated by the rio release workflow. DO NOT EDIT.
cask "rio" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bb5ce003d62b8366727bb88cc210525b880b8ca51f72215e2b204479ba34804a"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99880304930cf4053992be7afe3669f17827b213fd20d13b3ae5186bd37c82ad"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8602e5476d863d3fd7e6dda7e7b0d8cc69cf781fa7837df58a04ba8827868d71"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "686698db50fb8e4b8a404b47047f1a98b76f21c9d48edfdaafcb64619aac4180"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rio"
  desc "The rio CLI"
  homepage "https://github.com/rebaze/rio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rio"

  # No zap stanza required

end
