# This file was generated by the rio release workflow. DO NOT EDIT.
cask "rio" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "53c385c40d2f78d049ad4eb80e23c54363a27ab9ef13680f7509f3a9b6a1ce3c"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d317d99328eba649659b522de51b2af6764bb5a31f694b62cff1a601e7692971"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "064916ea81ea167348fdf8dd19f2aa164c4808b4eeb8d97e6413c4feb6e6255e"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d143ea8f7d384ffa4430987b0e20382c699ce1648177bc5b570ecdfdc787715"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rio"
  desc "The rio CLI"
  homepage "https://github.com/rebaze/rio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rio"

  postflight_steps do
    # The macOS binaries are ad-hoc signed by the Go toolchain, not
    # Developer ID signed or notarized, and Homebrew tags every cask
    # download with com.apple.quarantine. Gatekeeper SIGKILLs that
    # combination, so without this "brew install rebaze/tap/rio"
    # yields a binary that dies with signal 9 until the user approves
    # it by hand in System Settings. Strip the tag at install time.
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/rio"]
  end

  # No zap stanza required

end
