# This file was generated by the rio release workflow. DO NOT EDIT.
cask "rio" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1bd262ce2ce70cf7da31e44a2b60d6623bab2ecf27b572c78b1e4f502ffae150"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e643773284b3003cac9faf8310f5ccea7ee9efba3f3009f45f4df044da0c6513"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c4480342def37d3c440feff363b2f368ca7fa1fd98c0ea7ee84121d1aec08ae"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d13836166995aac0cfce8902bd4f1d43b2d75ff72c3b606b46ecad80c36472fd"
      url "https://github.com/rebaze/rio/releases/download/v#{version}/rio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rio"
  desc "The rio CLI"
  homepage "https://github.com/rebaze/rio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rio"

  postflight do
    # The macOS binaries are ad-hoc signed by the Go toolchain, not
    # Developer ID signed or notarized, and Homebrew tags every cask
    # download with com.apple.quarantine. Gatekeeper SIGKILLs that
    # combination, so without this "brew install rebaze/tap/rio"
    # yields a binary that dies with signal 9 until the user approves
    # it by hand in System Settings. Strip the tag at install time.
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/rio"]
  end

  # No zap stanza required

end
