# This file was generated by GoReleaser. DO NOT EDIT.
cask "scat" do
  name "scat"
  desc "Software Composition Analysis CLI — SBOM, vulnerability, and license scanning"
  homepage "https://github.com/rebaze/scat"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scat"

  on_macos do
    on_intel do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_darwin_amd64.tar.gz"
      sha256 "67e875b8c8587e6e6dc57c99fa2bef6c1299ea2e441b919468cbbc9d993dcf14"
    end
    on_arm do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_darwin_arm64.tar.gz"
      sha256 "d9cf379ba19b336edef7559a2769591f2106e21c97ce7a40be42e46ba0d31a19"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_linux_amd64.tar.gz"
      sha256 "50a32c4681e2f847f6bd1b07011ddc43e23f7934bcebfd71b0dcf0fbd0c212c7"
    end
    on_arm do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_linux_arm64.tar.gz"
      sha256 "bbca0a5f33da8acd7589814ffdec18f1c67b4f4b7eeae3698a51cc5793ba9732"
    end
  end

  # No zap stanza required
end
