# This file was generated by the scat release workflow. DO NOT EDIT.
cask "scat" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "bc8fb29e76e114c9d978d8ba18127dec57536cfcb34ccb4d10ec30eeecd7e6df"
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e4de37697ca1237e5558762c46e72ef6345f3bf1ffde12e4b6f472a0e78c687"
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38c971eab2e7e01012addbf7587726b7e512d31b53cfa1b1606754a836cfce17"
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d8ddf409a275b8b39fa2fc2a4986e2ab626c1e39d0cc3cca35d2d6292707b39"
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scat"
  desc "Software Composition Analysis CLI — SBOM, vulnerability, and license scanning"
  homepage "https://github.com/rebaze/scat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scat"

  # No zap stanza required

end
