# This file was generated by GoReleaser. DO NOT EDIT.
cask "scat" do
  name "scat"
  desc "Software Composition Analysis CLI — SBOM, vulnerability, and license scanning"
  homepage "https://github.com/rebaze/scat"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scat"

  on_macos do
    on_intel do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_darwin_amd64.tar.gz"
      sha256 "afdb34bcc7b6c5769623a073e462f99a7e7246ffcb85c81895454a8a3ed87d4c"
    end
    on_arm do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_darwin_arm64.tar.gz"
      sha256 "217093d75fda5bdccf46578a2ecdeff44880d7977c83126ec14fea9d11ac662f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_linux_amd64.tar.gz"
      sha256 "c22b1facf63e8dfc41bd8b799a0a57a9dbb821c5f95a38929228b20d30fa7a81"
    end
    on_arm do
      url "https://github.com/rebaze/scat/releases/download/v#{version}/scat_#{version}_linux_arm64.tar.gz"
      sha256 "e23ac33f50c5f4024e29f827696f7d676f1194e45c9bfa9c7b97a494e8438ad3"
    end
  end

  # No zap stanza required
end
